web:
  image: php:5.6-apache
  volumes:
    - ./upload/:/var/www/html/
  links:
    - mysql
mysql:
  image: mysql
  volumes:
    - ./data/mysql:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD:123456
